import datetime

from sqlalchemy import Date, ForeignKey, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class Company(Base):
    """A public company, identified by its permanent SEC CIK, not ticker.

    Tickers are reused after delisting and change on rebrands/relistings —
    CIK never is. See CONTEXT.md "Company" / "Ticker" and ADR-0001.
    """

    __tablename__ = "companies"

    # SEC CIKs are numeric; the familiar 10-digit zero-padded form
    # (e.g. "0000320193") is a display/URL format, not the stored value.
    # autoincrement=False: CIK is always assigned externally by the SEC,
    # never generated by us — an insert without one should error, not
    # silently get a meaningless sequential value.
    cik: Mapped[int] = mapped_column(primary_key=True, autoincrement=False)
    ticker: Mapped[str] = mapped_column(String(10), unique=True, index=True)
    name: Mapped[str] = mapped_column(String(255))
    sector: Mapped[str | None] = mapped_column(String(100))
    gics: Mapped[str | None] = mapped_column(String(100))
    ipo_date: Mapped[datetime.date | None] = mapped_column(Date)

    aliases: Mapped[list["CompanyAlias"]] = relationship(
        back_populates="company", cascade="all, delete-orphan"
    )


class CompanyAlias(Base):
    """A curated brand/colloquial name mapped to its canonical Company.

    Search-only (e.g. "Google" -> Alphabet Inc.) — never used as identity.
    See CONTEXT.md "Company Alias".
    """

    __tablename__ = "company_aliases"
    __table_args__ = (
        # Ingestion re-runs (e.g. re-pulling SEC's bulk file) must be able
        # to insert-if-absent without creating duplicate alias rows.
        UniqueConstraint("alias", "company_cik", name="uq_company_alias"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    alias: Mapped[str] = mapped_column(String(255), index=True)
    company_cik: Mapped[int] = mapped_column(ForeignKey("companies.cik"))

    company: Mapped["Company"] = relationship(back_populates="aliases")
